# Generated by Django 4.2.23 on 2025-09-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
